### ISSUE TITLE
Do not provide the feature `env`

### ISSUE THREAD

**Issue by tarsius** [antham/helm-backup#22]
Emacs comes with a library which provides `env` so your package should not contain a library which does the same. Maybe you could rename it to `helm-backup-env`?

**Comment by tarsius** [comment]
Your `eyuml` package has the same issue.

**Comment by antham** [comment]
It's only for testing purpose, it's not included in melpa package for instance, only helm-backup.el matter. The same for eyuml.

**Comment by antham** [comment]
Have a look here => https://github.com/cask/cask/blob/master/features/support/env.el

**Comment by tarsius** [comment]
I know. But not everyone uses `package.el`. If you clone the repository as a submodule and load it from there, then you might end up loading your `env.el` instead of the real thing. Of course you don't have to address this if you don't want to, but it would be nice if you did.

**Comment by antham** [comment]
That make sense, but I guess I'm not the only know who is going to have this issue if you follow the example from the official project.

**Comment by tarsius** [comment]
> if you follow the example from the official project.

Didn't know that. And I am a bit surprised because of the several thousand packages on the Emacsmirror yours are the only ones which have this issue. If more people start following these instructions then I will have to beg the Cask maintainers to make changes. But that might very well fail because their position on similar issues was "if you don't use `package.el`, then that's your own fault and we will do absolutely nothing to make live easier for you" (slight exaggeration, but that's what it boils down to).

So lets leave this open for a while. I am currently dealing with *many* issues in packages on the Emacsmirror, so that I can re-announce it in a few days. And there are other issues which are easier to address so I will concentrate on those (I won't be able to address everything anyway).

**Comment by antham** [comment]
Well, if you pick a project randomly from rejeep github, for instance https://github.com/rejeep/prodigy.el with 200 stars so a project with some success, you have it =>  https://github.com/rejeep/prodigy.el/blob/master/features/support/env.el

**Comment by antham** [comment]
I tried to change but test don't work anymore, so I have to dive into what's going on to understand the issue.

**Comment by tarsius** [comment]
Turns out the right thing to do, is to not provide a feature. I've done that in #23.
