### ISSUE TITLE
No track files that are already tracked

### ISSUE THREAD

**Issue by humitos** [antham/helm-backup#26]
I noticed that where I'm editing a file that already belong to a project with vcs (git, hg, bz, etc) that I'm working on, `helm-backup` keeps also a track of this file.

I think this could be something interesting for some people at certain point but on the other hand it's also a way to _duplicate everything_. Maybe a good idea is to have a setting to be able to configure this and do not enable `helm-backup` when the file is already into a project.

**Comment by antham** [comment]
This plugin and a vcs don't have the same purpose, in a vcs you keep track of changes when you decide to do so, this plugin is a backup system so it will record any changes (if you configure it to do so) occuring on a file to be able to rollback at any changing point. It's possible to specify a folder you don't want to track if you need.
