### ISSUE TITLE
Multiple frames opened

### ISSUE THREAD

**Issue by humitos** [antham/helm-backup#27]
When I call `helm-backup` and I hit `TAB` multiple frames are opened. I'm not sure if this is on purpuse or not; but I think it's really annoying.

![captura de pantalla_2017-06-18_13-19-28](https://user-images.githubusercontent.com/244656/27263907-cdcb498a-5428-11e7-9b3c-9f8e2eedb384.png)

By hitting `TAB` I would expect to see the diff of the last version on the same frame that I am, maybe... Or at least, something less intrusive.

**Comment by antham** [comment]
Hmm strange I don't have this behaviour everything is opened in the same frame on my emacs, can you tell me more about your config ?

**Comment by humitos** [comment]
I don't know what's exactly causing this.

My config is kind of big, but it's very splited by plugin at https://github.com/humitos/emacs-configuration

**Comment by antham** [comment]
I'm clausing this because no one else report the problem, I guess it's a matter of a particular configuration
