### ISSUE TITLE
function helm-backup fails if filename contains non-standard characters (ä,ô,...) & git init doesn't work

### ISSUE THREAD

**Issue by kiuuik** [antham/helm-backup#29]
First of all thanks for this great package. But I have two problems.

Today I tested the latest version of helm-backup and its dependencies from Melpa with a new profile on Fedora26.
My emacs version is "25.2.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.16) of 2017-07-17". 
Details about my installed packages are in [1] and my init.el is in [2]

1. **helm-backup-versioning doesn't create a new git repo if necessary**. If outside of emacs I run "git init" this packages works as expected (apart from the following problem).

2. **when a file name contains non-standard** (maybe non-ascii (?)) **characters like ô,ä,ö,ü the function helm-backup fails** with this error message: "No filename associated with buffer, file has no backup yet or filename is blacklisted". The function helm-backup-versioning seems to work properly because if I check the contents of the git repo outside of emacs with the command 'git log' I see a commit for every save. 

I also tested with a different linux distro but the problems persist.

----
[1] installed packages and their dependencies:
````
  helm-backup        20170625.328  installed
  async              20170610.2241 dependency
  helm               20170724.2137 dependency
  helm-core          20170727.1245 dependency
  popup              20160709.729  dependency
  s                  20170428.1026 dependency
````

[2] my init.el:
````
(package-initialize)

(custom-set-variables
 '(package-selected-packages (quote (restart-emacs helm-backup))))
(custom-set-faces
 )

(setq package-archives
      '(("MELPA"        . "https://melpa.org/packages/"))
)

(add-hook 'after-save-hook 'helm-backup-versioning)
````

**Comment by antham** [comment]
Hi thanks for your report.

I know where your second problem come from, but the first one, I have no clue. I cannot repoduce with the same config you gave. What git version do you use ? Do you have any error messages poping somewhere ? Have you tried to customize your path in customize-group  "helm-backup" to see what happen ?

**Comment by kiuuik** [comment]
thanks for your quick reply.

About my first problem: Even if others can reproduce it I don't think that it's of interest because it can be fixed by running one command once. Probably it's some mistake by me or I have a weird setup....

I can reproduce it. 
- I tried on Debian9 with emacs from the debian repo (version 25.1.1) and it works as expected. 
- I tried with Debian9 with a self compiled emacs 25.2.1. It is not working as in my initlal report. 
- I did a second try in fedora26 and I have the same problem.

Using `(setq helm-backup-path "/home/kiuuik/helmtest")` doesn't change anything. 
In fedora 26 I use git version 2.13.3.
I don't see any error messages.

Details about my second try in fedora26: I ran "dnf update" and rebooted my machine and deleted the folders .emacs.d  and .helm-backups. Then I created another init file ~/emacs.d/init.el with another text editor and put in the contents from my first command (apart from the last line). Then I started emacs and ran list-packages and installed helm-backup. Then I closed emacs and inserted the after-save-hook to my init. Then I restarted emacs and saved some files a couple of times. Then I checked on my terminal (konsole) by running `ls -al` in ~/.helm-backup. There is no .git folder.  

In emacs I went to *messages*. This is what it looks like after a couple of saves

````
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/git-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Mark set
Auto-saving...done
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
Making completion list...
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
Saving file /home/kiuuik/torte...
Wrote /home/kiuuik/torte
You can run the command ‘switch-to-buffer’ with C-x b [2 times]
````

After running "git init" from "M-x shell" once everything works as expected.

**Comment by antham** [comment]
Have you tried to force full binary path in customize-group through "helm-backup-git-binary" variable ?

**Comment by kiuuik** [comment]
Today everything works for me in fedora26.

I started over today and tried to exactly follow the steps I described in my last post. Now it works. I'm not aware that I did anything different this time. I didn't need to adjust helm-backup-path or helm-backup-git-binary.

Debian9 with 25.2 still isn't working for me. I added `(setq helm-backup-git-binary "/usr/bin/git")` (after checking the git location with `whereis git`) but it didn't help. But probably I make some errors somewhere.

Thanks again for you patience and help. I look forward to the newest version.

**Comment by antham** [comment]
Can you tell me if the new version solve your problem ?

**Comment by kiuuik** [comment]
The new version solves my problem with umlauts. Thank you very much for quick help!

**Comment by antham** [comment]
👍
