### ISSUE TITLE
Split up package

### ISSUE THREAD

**Issue by walseb** [antham/helm-backup#36]
Hi! Would you be willing to split up this package into two packages, one with the backup backend and another with the helm frontend as suggested here https://github.com/melpa/melpa/pull/6476 ? It seems like it would only require the removal of like two functions but renaming the package among with all functions and submitting a new package to melpa would probably be pretty time consuming. It would be nice to have the possibility of this confirmed before putting my ivy frontend on melpa

**Comment by antham** [comment]
Hi,
sorry I saw the ping from melpa repository but didn't answer yet. Let me check what I can do about that.

**Comment by antham** [comment]
After checking, it will require a bit of work to have something done in a proper way, I created this repository https://github.com/antham/git-backup to store the library

**Comment by antham** [comment]
@walseb Just to let you know what's going on. I have a library with all unit tests passing, I still need a bit of work to have something clean.

**Comment by antham** [comment]
Sorry for this delay, i opened the PR on melpa  => https://github.com/melpa/melpa/pull/6581

**Comment by walseb** [comment]
Great! I will update my package next weekend or so.
